# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # parametro de entrada, el nombre a quien saludar
    description: 'Who to greet'
    required: true
    default: 'Mundo'
outputs: 
  time: # parametro de salida, se puede recoger en un workflow.yml
    description: 'The time we greeted you'
runs:
  using: 'docker' # Tipo de runner "docker"
  image: 'Dockerfile' # Referencia relativa al Dockerfile https://github.com/constanap/hello-world-docker-action/blob/main/Dockerfile
  args:
    - ${{ inputs.who-to-greet }}
