name: detect-secrets #Comentario estupido
on: [push]
jobs:
  detect-secrets-market:
    runs-on: [self-hosted, Linux, X64, personal, loquesea]
    steps:
      - uses: actions/checkout@v2
      - name: Secret Detector
        uses: evanextreme/detect-secrets-action@1.0.0
