name: detect-secrets
on: [push]
jobs:
  detect-secrets-market:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Secret Detector
        uses: evanextreme/detect-secrets-action@c584bb1731d5ca59f3adce594afac678c56aabfc
